### ISSUE TITLE
install command fails to find the binary

### ISSUE THREAD

**Issue by j605** [techwiz24/aur-ghetto-skype#2]
The last install command in `package()` fails with 

``` bash
install: cannot stat '/tmp/ghetto-skype/src/../ghetto-skype': No such file or directory
```

**Comment by nlowe** [comment]
Did you change your `$srcdir`? I am unable to repro this. What AUR helper, if any, are you using?

**Comment by j605** [comment]
I am using just makepkg and made no edits to the PKGBUILD.

**Comment by j605** [comment]
Like you said, my `$srcdir` is not present in the directory where the PKGBUILD is present.

**Comment by nlowe** [comment]
Please try `1.4.1` which I've just uploaded to the AUR. I inlined the launcher file in the `pkgbuild` so if you happen to build your packages in a different directory structure than `pacaur` does, this should no longer cause issues.

**Comment by j605** [comment]
It works now. But a slight change in the PKGBUILD is needed as electron is now in the community repository.
