### ISSUE TITLE
Package for 1.5.0

### ISSUE THREAD

**Issue by nlowe** [techwiz24/aur-ghetto-skype#3]
The package instructions changed for 1.5.0, which should ***hopefully*** make it easier to package

### TODO:
- [ ] Update `pkgbuild` with new dependencies
    - `libicns` from the AUR
- [x] Figure out why the build instructions fail (stanfieldr/ghetto-skype#115)

**Comment by nlowe** [comment]
Build failure was a problem with the `fish` shell. We'd probably want to use the `dir` target anyways since the pacman package that `fpm` generates is pretty lacking. Also, I still need to figure out how to make it use the system `electron` instead of bundling another copy (electron-userland/electron-builder#1041)...

**Comment by develar** [comment]
> I still need to figure out how to make it use the system electron instead of bundling another copy

If you don't want to bundle electron executable as part of your app — it is a wrong idea. It is better just to pack it. It is only 50 MB and you will be sure that your apps works.

> ce the pacman package that fpm generates is pretty lacking.

Could you please file issue to fpm?
